export const municipalDirectorates = [
  'Ulaşım Hizmetleri Müdürlüğü',
  'Fen İşleri Müdürlüğü',
  'Afet İşleri ve Risk Yönetimi Müdürlüğü',
  'Basın Yayın ve Halkla İlişkiler Müdürlüğü',
  'Bilgi İşlem Müdürlüğü',
  'Destek Hizmetleri Müdürlüğü',
  'Emlak ve İstimlak Müdürlüğü',
  'Gelirler Müdürlüğü',
  'Gençlik ve Spor Hizmetleri Müdürlüğü',
  'Hal Müdürlüğü',
  'Hukuk İşleri Müdürlüğü',
  'İklim Değişikliği ve Sıfır Atık Müdürlüğü',
  'İmar ve Şehircilik Müdürlüğü',
  'İnsan Kaynakları ve Eğitim Müdürlüğü',
  'İşletme ve İştirakler Müdürlüğü',
  'İtfaiye Müdürlüğü',
  'Kadın ve Aile Hizmetleri Müdürlüğü',
  'Kent Tarihi, Tanıtım ve Turizm Müdürlüğü',
  'Kültür, Sanat ve Sosyal İşler Müdürlüğü',
  'Makine İkmal Bakım ve Onarım Müdürlüğü',
  'Mali Hizmetler Müdürlüğü',
  'Özel Kalem Müdürlüğü',
  'Park ve Bahçeler Müdürlüğü',
  'Rehberlik ve Teftiş Kurulu Müdürlüğü',
  'Ruhsat ve Denetim Müdürlüğü',
  'Sosyal Hizmetler Müdürlüğü',
  'Strateji Geliştirme Müdürlüğü',
  'Su ve Kanalizasyon Müdürlüğü',
  'Temizlik İşleri Müdürlüğü',
  'Veteriner İşleri Müdürlüğü',
  'Yapı Kontrol Müdürlüğü',
  'Yazı İşleri Müdürlüğü',
  'Zabıta Müdürlüğü',
] as const

export function normalizeResponsibleUnits(units?: string[], legacyUnit?: string): string[] {
  return [...new Set((units?.length ? units : legacyUnit ? [legacyUnit] : []).filter(Boolean))]
}
