export const kutahyaNeighborhoods = [
  '100. Yıl',
  '30 Ağustos',
  '75. Yıl',
  'Ağaçköy',
  'Akkent',
  'Alayunt',
  'Alipaşa',
  'Andız',
  'Aydoğdu',
  'Bahçelievler',
  'Balıklı',
  'Bölücek',
  'Börekçiler',
  'Bozcahöyük',
  'Çalca',
  'Cedit',
  'Cemalettin',
  'Civli',
  'Cumhuriyet',
  'Dumlupınar',
  'Enne',
  'Evliya Çelebi',
  'Fatih',
  'Fuatpaşa',
  'Gaybiefendi',
  'Geven',
  'G. Kemal',
  'Gültepe',
  'Güveççi',
  'Hacıazizler',
  'Hamidiye',
  'Hilalkent',
  'İkizüyük',
  'İnköy',
  'İshak Seydi',
  'İstiklal',
  'Kirazpınar',
  'Kırgıllı',
  'Kumarı',
  'Lala Hüseyin Paşa',
  'Maltepe',
  'Maruf',
  'Mecidiye',
  'Mehmet Akif Ersoy',
  'Meydan',
  'Müderris',
  'Okçu',
  'Ok Meydanı',
  'Osmangazi',
  'Parmakören',
  'Paşam Sultan',
  'Perli',
  'Pirler',
  'Şair Şeyhi Dumlupınar',
  'Saray',
  'Servi',
  'Seyitler',
  'Siner',
  'Sofu',
  'Sultanbağı',
  'Vefa',
  'Yeni Bosna',
  'Yenidoğan',
  'Yıldırım Beyazıt',
  'Yoncalı',
  'Yunusemre',
  'Zafertepe',
  'Ziğra',
] as const
